### ISSUE TITLE
PTY between Windows and Linux

### ISSUE THREAD

**Issue by RAF-87** [WangYihang/Platypus#38]
From Windows 10 to Linux, PTY works, but sets terminal rows and columns always both to 0.
So things like nano are not usable.

**Comment by WangYihang** [comment]
Thank you so much for reporting this issue.
It's hard to track server terminal size and send it via reverse shell connection. When we want to change the reverse shell terminal size via reverse shell connection without introducing other communication channels, the only way is to send `stty size [rows] [columns]`. This increases the cost to track the terminal state and won't work correctly in some cases.
For example:
1. Attacker is using vim of the current session
2. The attacker resizes the terminal to `rows = 40, columns = 80`
3. Platypus sends `stty size 40 80` via reverse shell connection, but in vim, this string will not be considered as a command but the input of the vim.
So, for simplicity and usability, the default action is just to ignore the platypus side terminal size. When the platypus terminal contains the victim terminal size, things will be correct.

To achieve your idea, we need a customed client binary that will be sent and executed on the victim machine. This functionality will be released soon.

**Comment by WangYihang** [comment]
This feature was supported In v1.4.1. Thank you for requesting this feature, feel free to try it and leave some feedback.
Now, as the gif shows below, Platypus will start two different listeners by default.

* `13338` for raw reverse shell listener, which provides an `Upgrade` Button on the client. It will upgrade the client to the TLS encrypted channel.
* `13337` for the private encrypted channel, in which you can try to start a shell interactively with an automatically updated window size. (Only works on *nix like operating system)

![encrypted2](https://user-images.githubusercontent.com/16917636/116522292-9daa9700-a907-11eb-86dd-935ce5a99d0f.gif)

**Comment by RAF-87** [comment]
Awesome, thank you!

**Comment by RAF-87** [comment]
To edit default ports, is there an option yet or only modifying the code? Or every time I need to end and restart the listeners manually?

**Comment by WangYihang** [comment]
The first time you run `Platypus`, the config file will be generated at the current folder named `config.yml`.
The template of the config file is at [./lib/runtime/config.example.yml](https://github.com/WangYihang/Platypus/blob/master/lib/runtime/config.example.yml), as you can see: 
```yaml
servers: 
  - host: "0.0.0.0"
    port: 13337
    # Platypus is able to use several properties as unique identifier (primirary key) of a single client.
    # All available properties are listed below:
    # `%i` IP
    # `%u` Username
    # `%m` MAC address
    # `%o` Operating System
    # `%t` Income TimeStamp
    hashFormat: "%i %u %m %o"
    encrypted: true
  - host: "0.0.0.0"
    port: 13338
    # Using TimeStamp allows us to track all connections from the same IP / Username / OS and MAC.
    hashFormat: "%i %u %m %o %t"
```
You can add as many as you want servers to listen, also, you can change the properties of any server.
For example: 
```yaml
servers:
  - host: "0.0.0.0"
    port: 10000
    hashFormat: "%i %u %m %o %t"
  - host: "0.0.0.0"
    port: 10001
    hashFormat: "%i %u %m %o %t"
  - host: "0.0.0.0"
    port: 10002
    encrypted: true
    hashFormat: "%i %u %m %o %t"
  - host: "0.0.0.0"
    port: 10003
    encrypted: true
    hashFormat: "%i %u %m %o %t"
```
In the config file above, port `10000` is a plain reverse shell listener, and the ports `10001~10003` are the encrypted listener.
