### ISSUE TITLE
`DisableHistory` as a config entry of servers.

### ISSUE THREAD

**Issue by WangYihang** [WangYihang/Platypus#50]
> Seems to be inconsistent between distributions, normally you would get bash commands stored in memory until written to history file. But in this case seems to just disable them completely (which is not bad).
> I would leave it personally as you done and just allow it on the config as I said above.
> Let me know what you think.

Good idea!

_Originally posted by @WangYihang in https://github.com/WangYihang/Platypus/issues/46#issuecomment-843266355_

**Comment by WangYihang** [comment]
@RAF-87, Solved.

```yml
servers: 
  - host: "0.0.0.0"
    port: 13337
    ...
    encrypted: true
    disable_history: true
  - host: "0.0.0.0"
    port: 13338
    ...
    disable_history: true
```
