### ISSUE TITLE
Docker container in non host mode wrong ip

### ISSUE THREAD

**Issue by miathedev** [WangYihang/Platypus#60]
#### Description

When using the docker container in non host mode, the external ip is detected as the containers network ip. There should be a optional setter in the config.yml:

- external ip
- external domain name (for first time setup for example)

Example:
detected: 172.18.0.2
real: 90.X.X.X (public host ip on e.g. eth0)

#### Reproduce

docker-compose.yml
```
version: '3'

services:
  app:
    container_name: platypus
    build: .
    tty: true
    #network_mode: host
    ports:
      - 127.0.0.1:7331:7331
      - 1337-1400:1337-1400
      - 13339:13339
    entrypoint: tmux new -s platypus ./platypus
    volumes:
      - ./config.yml:/app/config-v1.4.2.yml
```
```docker-compose up -d```

#### Expected behavior

IP or domain for connecting each server in the ui is displayed correctly (in list and setup) and services are connectable to the docker hosts public ip or domain

#### Current behavior

IP is falsely claimed to be the docker containers ip in the bridge network. No connection possible at all for reverse shell. Using domains for first time client setup is not possible

#### Screenshots/Terminal log

![screenshot](https://user-images.githubusercontent.com/43496606/124990792-1c772b00-e041-11eb-8536-1160d40c3a5b.png)

#### Environments
 - OS: Ubuntu 18.04.1 LTS
 - Version: 8cf76427c6e17f96006869add59d09ab0364c2eb (master-08.07.21)

With kind regards,
miathedev
